### ISSUE TITLE
Newest Version from PSOc Project for UD3.1c

### ISSUE THREAD

**Issue by TeslaInfinity** [Netzpfuscher/UD3#41]
hello, its possible to update the version wich is actually online for download ?
online version from PSOc project file for UD3 is from 2021 :)

please upload newest version for the UD3.1c from December 2023 or newer.
for TQFP 100

thank u very much :)

best regards 
Lucien

**Comment by Netzpfuscher** [comment]
I merged the digipot branch into master. That's the latest version for now.

**Comment by TeslaInfinity** [comment]
Hello :)

But if I open the project in psoc creator, the pins are not used.

Can u send the project file please per Mail ?
Thank u.

Mit freundlichen Grüßen
Tunger L.


> Am 28.02.2024 um 12:43 schrieb Jens Kerrinnes ***@***.***>:
> 
> I merged the digipot branch into master. That's the latest version for now.
