### ISSUE TITLE
Lead time still have no effect. 

### ISSUE THREAD

**Issue by teslamusicband** [Netzpfuscher/UD3#8]
Lead time still have no effect. I flashed a TTerm branch from last of Nov 4, 2020 commit of UD3 rep. Teslaterm is from malte0811's Oct 25, 2020 last commit of electron-ts branch.

https://www.youtube.com/watch?v=Frnzz3h5iHA

**Comment by Netzpfuscher** [comment]
I double checked the calculations. I see no error. In the first sequence in the Video I see around 1000ns lead time but it switches way to early. If the driver doesn't drive at 0 lead time I think there is something different wrong. Like the start_freq please double check your primary resonant freq.
